doc:
  kind: "rule"
  id: "branch-innovation-contribution"
  version: "1.0.0"
  status: "active"
  created: "2025-09-10"

trigger: "Branch opens an [Upstream-Proposal] discussion"

actors:
  - "branch_maintainers"
  - "core_reviewers"
  - "ai_assistants"

workflow:
  research:
    - "Fetch and diff branch governance against core"
    - "Identify novel mechanisms and empirical results"
  validate:
    - "Check alignment with principles"
    - "Detect breaking changes and migration needs"
  evidence:
    - "Collect usage metrics and failure cases"
    - "Survey branch participants"
  cross_testing:
    - "Create temporary evaluation branch"
    - "Invite other branches to trial"
  integration:
    - "If approved, draft merge plan and credits"
    - "Update changelog and announce network-wide"

evaluation_criteria:
  - "≥14 days of branch usage"
  - "No violations of immutable foundations"
  - "Positive impact on clarity, safety, or velocity"
  - "Low migration friction"

outputs:
  - type: "recommendation"   # adopt|adapt|decline
  - type: "integration_plan"
  - type: "attribution"
