doc:
  kind: "rule"
  id: "discussion-process"
  version: "1.0.0"
  status: "active"
  created: "2025-09-10"

trigger: "A governance topic is marked for discussion"

phases:
  opening:
    must:
      - "Create public thread with scoped question and context"
      - "Declare intended category (term/rule/principle/meta-rule)"
  exploration:
    must:
      - "Invite explicit counter-arguments (dialectic)"
      - "AI syntheses every 48h (summary + unresolved tensions)"
  convergence:
    must:
      - "Propose candidate synthesis responding to objections"
      - "Confirm readiness for vote (cooling period applies)"
  conclusion:
    must:
      - "Publish final synthesis"
      - "Link any resulting proposals"

guardrails:
  quorum_visibility: true
  code_of_conduct: "Good-faith participation; no dominance; moderator may re-scope"

references:
  principles: ["#dialectic-evolution", "#transparency"]
  terms: ["discussion", "participant", "consensus"]
