doc:
  kind: "rule"
  id: "proposal-process"
  version: "1.0.0"
  status: "active"
  created: "2025-09-10"

trigger: "Thread tagged [Proposal]"

steps:
  - name: "intake"
    must:
      - "Identify artifact(s) and category"
      - "Provide structured diff + rationale + impact"
      - "Declare proposed version bump"
  - name: "conflict-scan"
    must:
      - "Search prior proposals"
      - "Detect conflicting rules/terms"
  - name: "validation"
    must:
      - "Check immutable foundations"
      - "Check principle alignment"
  - name: "discussion"
    must:
      - "Hold open per category minimum days (see meta-rule)"
      - "Publish AI syntheses"
  - name: "decision"
    must:
      - "Verify quorum and threshold"
      - "Publish vote breakdown and rationales"
  - name: "implementation"
    must:
      - "Merge changes"
      - "Tag release"
      - "Update changelogs and site pages (mission/how-it-works/etc.)"

outputs:
  - "approved|rejected|revise"
  - "pull_request_url"
  - "markdown_summary"
